robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [Joint_1, Joint_2, Joint_3, Joint_4, Joint_5, End_effector_Joint]

#Controller to control end effector joints
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [Gripper_arm_left_Joint, Gripper_arm_right_Joint]

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50